druid: Avoid using javascript filter
Netflix-Skunkworks/iep-apps pull request #262
Opened 2020-10-06 02:30 UTC by bsyk

Use regex filter with lowercase extraction function and lowercase the regex query. Extraction functions are applied to the value prior to applying the filter, but the matched value is returned unchanged.

2020-10-06 13:42 UTC, brharrington requested changes

2020-10-06 13:42 UTC, brharrington commented on atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidFilter.scala
> +      case Query.RegexIgnoreCase(k, v)  => Reic(k, s"^$v".toLowerCase())
Performing `toLowerCase` on an arbitrary regex pattern is not guaranteed to be correct. For example inverse character classes (`\D` matches non-digits where `\d` matches digits) are often uppercase.

2020-10-07 00:32 UTC, bsyk commented on atlas-druid/src/main/scala/com/netflix/atlas/druid/DruidFilter.scala
> +      case Query.RegexIgnoreCase(k, v)  => Reic(k, s"^$v".toLowerCase())
Ah yes, very good point. Don't know what I was thinking!
Took some digging, but I found a way to do case-insensitive searches directly.

2020-10-07 00:54 UTC, brharrington approved these changes

2020-10-07 00:55 UTC, merged