Add ExecutedVersion Dimension and three new PC metrics
Netflix-Skunkworks/iep-apps pull request #548
Opened 2024-05-01 22:24 UTC by mpalriwal-Netflix

2024-05-01 22:35 UTC, manolama requested changes

2024-05-01 22:35 UTC, manolama commented on atlas-cloudwatch/src/main/resources/lambda.conf
> +        "ExecutedVersion"
Add this tag to the `reference.conf` mapper as something like `aws.executed.version`

2024-05-01 22:38 UTC, mpalriwal-Netflix commented on atlas-cloudwatch/src/main/resources/lambda.conf
> +        "ExecutedVersion"
Updated

2024-05-02 03:02 UTC, manolama approved these changes

2024-05-02 03:03 UTC, merged